image:
  name: atlassian/default-image:2

pipelines:
    branches:
        dev:
            - step:
                services:
                    - docker # Enable Docker for your repository
                name: Build and publish docker image.
                script:
                    # Modify the commands below to build your repository.
                    # Set the name of the docker image we will be building.
                    - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
                    - unzip awscliv2.zip
                    - ./aws/install
                    - export IMAGE_NAME="moris/${BITBUCKET_BRANCH}-rasa-${BITBUCKET_REPO_SLUG}"
                    # Build the docker image and push to . Dockerhub.
                    - docker build -t demo-pnb-backend .
                    - docker images
                    - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 912708290344.dkr.ecr.ap-south-1.amazonaws.com
                    - docker tag demo-pnb-backend:latest 912708290344.dkr.ecr.ap-south-1.amazonaws.com/demo-pnb-backend:latest
                    - docker push 912708290344.dkr.ecr.ap-south-1.amazonaws.com/demo-pnb-backend:latest
                    - aws ecs update-service --service demo-pnb-backend-service-z55lx98q --cluster talkk --force-new-deployment 