[project]
name = "pnb-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beanie>=1.30.0",
    "boto3>=1.39.2",
    "fastapi[standard]>=0.115.14",
    "jinja2>=3.1.6",
    "keybert>=0.9.0",
    "langchain-community>=0.3.27",
    "langchain-core>=0.3.67",
    "langchain-mongodb>=0.6.2",
    "langchain-openai>=0.3.27",
    "langchain-tavily>=0.2.10",
    "langgraph>=0.5.1",
    "langgraph-checkpoint-mongodb>=0.1.4",
    "langgraph-supervisor>=0.0.27",
    "markdown>=3.8.2",
    "motor>=3.7.1",
    "mysql-connector-python-rf>=2.2.2",
    "pandas>=2.3.1",
    "pdf2image>=1.17.0",
    "pdfkit>=1.0.0",
    "pymupdf>=1.26.3",
    "pymupdf4llm>=0.0.26",
    "pytesseract>=0.3.13",
    "python-multipart>=0.0.20",
]
