# from turtle import title
from pydantic import BaseModel, Field, HttpUrl
from typing import List, Literal


class Review(BaseModel):
    alert: Literal["no_risk", "medium_risk", "high_risk", "low_risk"] = Field(
        description="The alert as per the 'credit_assist_agent'"
    )
    title: str = Field(
        description="The title of the review as in the response by the 'credit_assist_agent'"
    )
    message: str = Field(
        description="The reason of the alert by the 'credit_assist_agent'. Make sure it is an issue or a discrepancy explicitly."
    )


class AgentLifeCycleReasoning(BaseModel):
    outcome: str = Field(description="The single outcome text generated by agent")
    status: bool = Field(
        description="The status of the outcome derived by the outcome text"
    )


class AgentLifeCycle(BaseModel):
    agent_name: Literal[
        "Document Verification Agent",
        "Tax Data Agent",
        "Company Financial Agent",
        "Complaince Reviewer Agent",
        "Credit Assist Agent",
    ] = Field(
        description="The name of the agent. Please append 'agent' tag to the names and humanise it.\
        Refer to the agent used section in the response and make sure all the agents are present irrespective of their function."
    )
    reasoning: List[AgentLifeCycleReasoning] = Field(
        description="The outcomes of the action performed by the agent and what the actions have been done in the tasks as per the reviews generated.\
        Provide in a checklist format with ticked items or crossed items in each line",
        default=[],
    )


class DocumentChecklist(BaseModel):
    document_name: str
    file_url: str = Field(description="URL of the source file")
    isVerified: bool = Field(
        description="True if the document is verified otherwise False"
    )
    file_name: str = Field(
        description="Name of the file as received in the extracted contents"
    )


class Credit(BaseModel):
    review_set: List[Review] = Field(
        description="The review set in as in the response by the 'credit_assist_agent'"
    )
    agent_lifecycle: List[AgentLifeCycle] = Field(description="")
    documents_checklist: List[DocumentChecklist] = Field(
        description="The documents in the response"
    )
